### ISSUE TITLE
dashboard is not centred

### ISSUE THREAD

**Issue by PitcherTear22** [hardcoreplayers/dashboard-nvim#11]
When using nvim from a terminal (ie open terminal and type `nvim`) the dashboard is centred properly

But when using from a desktop shortcut `nvim.desktop`:
```
Exec=konsole -e nvim
Terminal=false
```
or  a neovim GUI ([neovide](https://github.com/Kethku/neovide) or [goneovim](https://github.com/akiyosi/goneovim)), it is not centred

See video:https://imgur.com/zpZJ6PF

**Comment by glepnir** [comment]
@PitcherTear22 P  Sorry  I don't work for gui neovim.

**Comment by PitcherTear22** [comment]
> @PitcherTear22 P Sorry I don't work for gui neovim.

It also doesn't work for desktop shortcut of terminal neovim

**Comment by glepnir** [comment]
I tested it on centos7 with gnome terminal  macos kitty  alacritty iterm2.  works fine.

**Comment by PitcherTear22** [comment]
hmm it is the same on gnome-terminal: https://imgur.com/eRymmMa

**Comment by PitcherTear22** [comment]
to be clear, it **is centred** when you open the terminal and then type `nvim`, the problem is only in desktop shortcuts : https://imgur.com/deQ8X5F

**Comment by glepnir** [comment]
Please test the startify behavior. because the centerd function same as startify.

**Comment by PitcherTear22** [comment]
Yes even vim-startify has this problem

**Comment by PitcherTear22** [comment]
You mean this right:
![image](https://user-images.githubusercontent.com/36493671/88521918-45123a80-d013-11ea-808c-c626c5b57409.png)

**Comment by glepnir** [comment]
So this is a wired problem. What is the problem with the inability to locate the shortcut. Maybe different terminals behave differently？

**Comment by PitcherTear22** [comment]
but gnome terminal works for you and doesnt for me

**Comment by glepnir** [comment]
I don't test the shortcut. the normal behavior open terminal then open neovim.

**Comment by PitcherTear22** [comment]
ok

**Comment by Neur1n** [comment]
In my case, the startup page shifts to the right when using neovim-qt. But then using `:Dashboard` command everything is centered. This does not happen with startify.

**Comment by p00f** [comment]
> This does not happen with startify.

are you using startify centred or to the left?

**Comment by Neur1n** [comment]
> > This does not happen with startify.
> 
> are you using startify centred or to the left?

Both are tested :)
