### ISSUE TITLE
run autocmd on dashboard?

### ISSUE THREAD

**Issue by prankousky** [hardcoreplayers/dashboard-nvim#12]
Hi,

I just installed `dashboard-vim` to replace `Startify` (or to see whether it can do that, because I just realized how much I rely on startify now that it is gone :D). I have not made up my mind yet, but it does seem really awesome; I just kinda miss seeing the recently edited files and opening them by number, but perhaps I can change my workflow. Anyway, that is not what this is about.

# Actual Question

**Is it possible to run autocmnds on the dashboard**? I use `Yggdroot/indentline`, which is configured to display tabs. This makes the dashboard look ugly, as there are "random" vertical lines where there should be noting at all. While I can manually run `IndentLineToggle`, I'd prefer to automatically run this when `dashboard-vim` is started (and ideally when it's closed again so I got my indentation visible in regular text files again).

I tried `:echo @%` to determine what the buffer is titled (will usually return something like `/home/me/.config/nvim/init.vim`), but it will return nothing / empty string for the dashboard when opening vim.

Btw., I just tested, and the very same happens when running `:Startify`, so this doesn't seem to be a bug per se, but it'd still be nice if there was a way to fix this.

Thank you for your help :)

**Comment by glepnir** [comment]
`let g:indentLine_fileTypeExclude = ['dashboard']`

**Comment by prankousky** [comment]
Thank you!
