### ISSUE TITLE
Customization?

### ISSUE THREAD

**Issue by Tintef** [hardcoreplayers/dashboard-nvim#22]
Hi! First, thanks for the awesome plugin!

I noticed that there's no way to override the commands used for the different shortcuts (if there's I wasn't able to find it).

For example, in order to find a work I prefer to use `Ag` instead of `Rg`.

Another example could be customizing the popup that appears when using `fzf`.

Are there any plans on adding this possibilities?

**Comment by glepnir** [comment]
@Tintef  It can be support use ag instead of rg in fzf.  I currently use floatwindow for fzf. Are you dissatisfied with it?

**Comment by Tintef** [comment]
@glepnir How would I change this plugin to use ag instead of rg? The only way I found to it was to manually [change it here](https://github.com/hardcoreplayers/dashboard-nvim/blob/master/autoload/dashboard/fzf.vim#L22).

I like the floatwindow, and it does looks nice. I have used it in the past but I found it a bit intrusive on my workflow, so I prefer to have it like this:

<img width="1680" alt="Screen Shot 2020-08-24 at 00 30 32" src="https://user-images.githubusercontent.com/17990217/91001017-07b4b480-e5a1-11ea-936c-ab266275882b.png">

**Comment by glepnir** [comment]
@Tintef  Ok I got your problem. I will add it support later.

**Comment by glepnir** [comment]
@Tintef  Please update and give it a test. I add two option `let g:dashboard_fzf_float` default is 1.disable is 0
`let g:dashboard_fzf_engine` default is rg, set ag.
```vim
let g:dashboard_fzf_float = 0
let g:dashboard_fzf_engine = 'ag'
```

**Comment by Tintef** [comment]
@glepnir The engine works great!

Disabling the floatwindows thorws this errors when trying to find a file/word:

```Error detected while processing /Users/tintef/.vim/bundle/dashboard-nvim/autoload/dashboard/fzf.vim:
line    6:
E117: Unknown function: s:snr
E116: Invalid arguments for function get
E15: Invalid expression: get(s:, 'snr', s:snr())
line    8:
E121: Undefined variable: s:snr
E15: Invalid expression: {'window': 'call '..s:snr..'fzf_window(0.9, 0.6, "Comment")'}
line   88:```

**Comment by glepnir** [comment]
Ok.Please update. Maybe fixed.

**Comment by glepnir** [comment]
Hey any update?

**Comment by glepnir** [comment]
I will close this issue, Because doesn't got reply long time. If you still have problem , I will reopen this issue.
