### ISSUE TITLE
Dashboard header has trailing whitespace

### ISSUE THREAD

**Issue by charego** [hardcoreplayers/dashboard-nvim#6]
Together with [vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace) the dashboard looks sad.

<img width="450" alt="whitespace" src="https://user-images.githubusercontent.com/5209296/84725005-35510200-af4f-11ea-90fb-5aff56b92f5c.png">

**Comment by glepnir** [comment]
@charego  Hmm.. does this behavior can reproduce with startify? because the header function same as startify.

**Comment by charego** [comment]
Works for me! The red highlighting under the shortcuts remains, but I'm guessing that is not related.

**Comment by glepnir** [comment]
@charego  check out this `hi Error` maybe it have a red bg color.

**Comment by charego** [comment]
Thanks!

**Comment by PitcherTear22** [comment]
@glepnir I want to disable https://github.com/Yggdroot/indentLine in dashboard, how do i do that? I tried 
```vim
autocmd! FileType dashboard let g:indentLine_enabled = 0
  \| autocmd BufLeave <buffer> let g:indentLine_enabled = 1
``` from [here](https://github.com/Yggdroot/indentLine#customization)

**Comment by glepnir** [comment]
`let g:indentLine_fileTypeExclude = ['dashboard']`

**Comment by alejandrodnm** [comment]
I just got hit by this by LazyVim changing to dashboard-nvim.

Instead of the autocmd you can do `vim.g.better_whitespace_filetypes_blacklist = { "dashboard" }`

```
  {
    "ntpeters/vim-better-whitespace",
    init = function()
      vim.g.better_whitespace_filetypes_blacklist = { "dashboard" }
      vim.g.better_whitespace_enabled = 1
      vim.g.strip_whitespace_on_save = 1
      vim.g.strip_whitespace_confirm = 0
      vim.g.strip_whitelines_at_eof = 1
      vim.g.show_spaces_that_precede_tabs = 1
    end,
  },
```
