### ISSUE TITLE
pwd is home

### ISSUE THREAD

**Issue by PitcherTear22** [hardcoreplayers/dashboard-nvim#9]
When opening recent files, `pwd` is home (`/home/chinmay`) instead of the directory of the current file

How to reproduce: Select any file from "recently opened" menu, then do `:pwd`
Expected: `pwd` is the directory of the opened file

**Comment by glepnir** [comment]
what fuzzyfind plugin do you used? vim-clap or fzf?

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/88455356-3f97e180-cea7-11ea-832c-4689cbd5ebfb.png)

**Comment by PitcherTear22** [comment]
> what fuzzyfind plugin do you used? vim-clap or fzf?

vim-clap

**Comment by glepnir** [comment]
what do you expect? only show the old files in current folder?

**Comment by PitcherTear22** [comment]
https://imgur.com/rYkIEOP

I expect the output of `:pwd` to be `/home/chinmay/.config`
![image](https://user-images.githubusercontent.com/36493671/88458360-24c76c00-ceab-11ea-860e-19e6b7eaaece.png)

**Comment by glepnir** [comment]
I think it's not problem with dashboard-nvim.  because you open vim in `~` path.

**Comment by PitcherTear22** [comment]
vim-startify works correctly: https://imgur.com/p7ykiMo

**Comment by glepnir** [comment]
@glepnir  Ok. I will look at it.

**Comment by glepnir** [comment]
@PitcherTear22  The startify will do the `lcd` command when you open file in startify.  dashboard-nvim use the command of fuzzyfind plugins. so we can check what should we do in vim-clap command `Clap history`.

**Comment by glepnir** [comment]
Can you test it with latest commit?

**Comment by PitcherTear22** [comment]
> Can you test it with latest commit?

Ok just a minute

**Comment by PitcherTear22** [comment]
It is fixed, thanks!

**Comment by glepnir** [comment]
@PitcherTear22  But it will has a problem with defx. because it change the pwd to current file dir not work dir.

**Comment by PitcherTear22** [comment]
Can you make it a config option then ?
Like `g:dashboard#change#pwd` (which defaults to 1)

**Comment by glepnir** [comment]
@PitcherTear22  What file explorer do you used?

**Comment by glepnir** [comment]
new option called `let g:dashboard_change_to_dir` default is 0 ,enable is 1

**Comment by PitcherTear22** [comment]
ok

**Comment by PitcherTear22** [comment]
> @PitcherTear22 What file explorer do you used?

I don't understand?
